FROM python:3.11-slim

WORKDIR /mlflow

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN pip install --no-cache-dir mlflow

EXPOSE 5000

CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--workers", "1", "--backend-store-uri", "sqlite:///mlflow.db", "--default-artifact-root", "/mlruns", "--allowed-hosts", "mlflow:*,localhost:*,127.0.0.1:*"]

